[package]
edition = "2021"
name = "tfhe-regex"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex-syntax = "0.6.28"
tfhe = { version = "*", features = ["boolean", "shortint", "aarch64-unix"] }
